spring:
  application:
    name: gaming-server-service-search
  data:
    solr:
      host: http://192.168.211.129:8983/solr
  datasource:
    druid:
      url: jdbc:mysql://192.168.211.129:3306/toutiao?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

dubbo:
  scan:
    base-packages: com.ooqiu.gaming.service.search.api
  application:
    id: gaming-server-service-search
    name: gaming-server-service-search
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    address: zookeeper://192.168.211.129:2181?backup=192.168.211.129:2182,192.168.211.129:2183