spring:
  application:
    name: gaming-server-service-article
  datasource:
    druid:
      url: jdbc:mysql://192.168.211.129:3306/toutiao?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.ooqiu.gaming.server.domain
    mapper-locations: classpath:mapper/*.xml

dubbo:
  scan:
    base-packages: com.ooqiu.gaming.service.article.api
  application:
    id: gaming-server-service-article
    name: gaming-server-service-article
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    address: zookeeper://192.168.211.129:2181?backup=192.168.211.129:2182,192.168.211.129:2183