spring:
  application:
    name: gaming-server-service-redis
  redis:
    database: 0
    # 单机使用，对应服务器ip
    host: 192.168.211.129
    # 密码，如果没有设置可不配
    # password:
    # 单机使用，对应端口号
    port: 6379
    # 池配置
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
   # HA 环境，上生产时使用
   # sentinel:
     # master: mymaster
     # 多个节点用“,”分割
     # nodes: 192.168.75.134:26379

dubbo:
  scan:
    base-packages: com.ooqiu.gaming.service.redis.api
  application:
    id: gaming-server-service-redis
    name: gaming-server-service-redis
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    address: zookeeper://192.168.211.129:2181?backup=192.168.211.129:2182,192.168.211.129:2183